# fly.toml app configuration file generated for lj-be on 2023-11-07T08:26:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lj-be"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
